// Generated by app-wabbit-dev setup. Do not edit by hand.
// managed-integrity-v1: FdyzkXe5k1e
//
// This file is generated from workspace configuration in root.clj.
// To change it, update root.clj and regenerate
// with the dev command, for example:
//   dev setup <project-or-repo>
// For durable imperative Gradle logic, use build.extra.gradle.kts beside this file.
// Direct edits to this file will be overwritten the next time setup runs.

repositories {
    google()
    mavenCentral()

    maven("https://jitpack.io")
}

group   = "one.wabbit"

version = "0.0.2"

plugins {
    scala

    id("maven-publish")

    id("com.vanniktech.maven.publish")
}

mavenPublishing {
    coordinates("one.wabbit", "scala-twokenize", project.version.toString())
    publishToMavenCentral()
    signAllPublications()
    pom {
        name.set("scala-twokenize")
        description.set("scala-twokenize")
        url.set("https://github.com/wabbit-corp/scala-twokenize")
        licenses {
            license {
                name.set("GNU Affero General Public License v3.0 or later")
                url.set("https://spdx.org/licenses/AGPL-3.0-or-later.html")
            }
        }
        developers {
            developer {
                id.set("wabbit-corp")
                name.set("Wabbit Consulting Corporation")

                email.set("wabbit@wabbit.one")

            }
        }
        scm {
            url.set("https://github.com/wabbit-corp/scala-twokenize")
            connection.set("scm:git:git://github.com/wabbit-corp/scala-twokenize.git")
            developerConnection.set("scm:git:ssh://git@github.com/wabbit-corp/scala-twokenize.git")
        }
    }
}

val localPublishRequested =
    gradle.startParameter.taskNames.any { taskName -> "MavenLocal" in taskName }

if (localPublishRequested) {
    tasks.withType<org.gradle.plugins.signing.Sign>().configureEach {
        enabled = false
    }
}

dependencies {
    implementation("org.scala-lang:scala3-library_3:3.6.4")

    testImplementation("org.scalatest:scalatest_3:3.2.19")
    testRuntimeOnly("org.junit.platform:junit-platform-engine:1.10.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.10.0")
    testRuntimeOnly("org.scalatestplus:junit-5-10_3:3.2.19.0")
}

java {
    targetCompatibility = JavaVersion.toVersion(21)
    sourceCompatibility = JavaVersion.toVersion(21)
}

val configuredVersionString = version.toString()

tasks.register("printVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        println(inputs.properties["configuredVersion"])
    }
}

tasks.register("assertReleaseVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(!versionString.endsWith("+dev-SNAPSHOT")) {
            "Release publishing requires a non-snapshot version, got $versionString"
        }
        val refType = System.getenv("GITHUB_REF_TYPE") ?: ""
        val refName = System.getenv("GITHUB_REF_NAME") ?: ""
        if (refType == "tag" && refName.isNotBlank()) {
            val expectedTag = "v$versionString"
            require(refName == expectedTag) {
                "Git tag $refName does not match project version $versionString"
            }
        }
    }
}

tasks.register("assertSnapshotVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(versionString.endsWith("+dev-SNAPSHOT")) {
            "Snapshot publishing requires a +dev-SNAPSHOT version, got $versionString"
        }
        require((System.getenv("GITHUB_REF_TYPE") ?: "") != "tag") {
            "Snapshot publishing must not run from a tag ref"
        }
    }
}

tasks {
    withType<Test> {
        jvmArgs("-ea")

        useJUnitPlatform {
            includeEngines("scalatest")
            testLogging {
                events("passed", "skipped", "failed")
            }
        }

    }
    withType<JavaCompile> {
        options.encoding = Charsets.UTF_8.name()
        options.release.set(21)
    }
    withType<Javadoc> {
        options.encoding = Charsets.UTF_8.name()
    }

    jar {
        setProperty("zip64", true)

    }
}

val extraBuildFile = file("build.extra.gradle.kts")
if (extraBuildFile.isFile) {
    apply(from = extraBuildFile)
}
