// Generated by app-wabbit-dev setup. Do not edit by hand.
// managed-integrity-v1: DUHrMZjifwx
//
// This file is generated from workspace configuration in root.clj.
// To change it, update root.clj and regenerate
// with the dev command, for example:
//   dev setup <project-or-repo>
// For local includeBuild and dependency-substitution overrides, use
// settings.local.gradle.kts beside this file.
// Direct edits to this file will be overwritten the next time setup runs.

rootProject.name = "scala-twokenize"

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()

    }
}

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()

    }
    plugins {
        id("org.jetbrains.kotlin.jvm") version "2.3.10"
        id("org.jetbrains.kotlin.js") version "2.3.10"
        id("org.jetbrains.kotlin.multiplatform") version "2.3.10"
        id("org.jetbrains.kotlin.plugin.serialization") version "2.3.10"
        id("org.jetbrains.kotlin.plugin.compose") version "2.3.10"
        id("com.android.application") version "8.12.0"
        id("com.android.library") version "8.12.0"
        id("com.android.kotlin.multiplatform.library") version "8.12.0"
        id("org.jetbrains.compose") version "1.9.1"
        id("com.gradleup.shadow") version "8.3.0"
        id("org.jetbrains.dokka") version "2.0.0"
        id("org.jetbrains.kotlinx.kover") version "0.9.3"
        id("com.vanniktech.maven.publish") version "0.36.0"
        id("org.jetbrains.intellij") version "1.17.2"
        id("org.jetbrains.intellij.platform") version "2.10.4"
        id("io.papermc.paperweight.userdev") version "2.0.0-beta.17"
        id("net.minecrell.plugin-yml.bukkit") version "0.6.0"

    }
}

val localSettingsFile = file("settings.local.gradle.kts")
if (localSettingsFile.isFile) {
    apply(from = localSettingsFile)
}
