// Generated by app-wabbit-dev setup. Do not edit by hand.
// managed-integrity-v1: TZ7XU5NsShf
//
// This file is generated from workspace configuration in root.clj.
// To change it, update root.clj and regenerate
// with the dev command, for example:
//   dev setup <project-or-repo>
// For local includeBuild and dependency-substitution overrides, use
// settings.local.gradle.kts beside this file.
// Direct edits to this file will be overwritten the next time setup runs.

fun String.parseWabbitBooleanFlag(flagName: String): Boolean =
    when (trim().lowercase()) {
        "true" -> true
        "false" -> false
        else -> error("$flagName must be true or false, got '$this'")
    }

val useLocalBuildOverrides =
    providers.gradleProperty("wabbit.useLocalBuildOverrides")
        .orElse(providers.environmentVariable("WABBIT_USE_LOCAL_BUILD_OVERRIDES"))
        .orElse(providers.gradleProperty("wabbit.applyLocalSettingsOverlay"))
        .orElse(providers.environmentVariable("WABBIT_APPLY_LOCAL_SETTINGS_OVERLAY"))
        .map { it.parseWabbitBooleanFlag("wabbit.useLocalBuildOverrides") }
        .orElse(true)
        .get()

val useMavenLocalArtifacts =
    providers.gradleProperty("wabbit.useMavenLocalArtifacts")
        .orElse(providers.environmentVariable("WABBIT_USE_MAVEN_LOCAL_ARTIFACTS"))
        .map { it.parseWabbitBooleanFlag("wabbit.useMavenLocalArtifacts") }
        .orElse(false)
        .get()

rootProject.name = "scala-twokenize"

dependencyResolutionManagement {
    repositories {
        if (useMavenLocalArtifacts) {
            mavenLocal {
                content {
                    includeGroup("one.wabbit")
                    includeGroupByRegex("one\\.wabbit\\..+")
                }
            }
        }
        google()
        mavenCentral()

    }
}

pluginManagement {
    val useLocalBuildOverridesInPluginManagement =
        providers.gradleProperty("wabbit.useLocalBuildOverrides")
            .orElse(providers.environmentVariable("WABBIT_USE_LOCAL_BUILD_OVERRIDES"))
            .orElse(providers.gradleProperty("wabbit.applyLocalSettingsOverlay"))
            .orElse(providers.environmentVariable("WABBIT_APPLY_LOCAL_SETTINGS_OVERLAY"))
            .map { value ->
                when (value.trim().lowercase()) {
                    "true" -> true
                    "false" -> false
                    else -> error("wabbit.useLocalBuildOverrides must be true or false, got '$value'")
                }
            }
            .orElse(true)
            .get()

    val useMavenLocalArtifactsInPluginManagement =
        providers.gradleProperty("wabbit.useMavenLocalArtifacts")
            .orElse(providers.environmentVariable("WABBIT_USE_MAVEN_LOCAL_ARTIFACTS"))
            .map { value ->
                when (value.trim().lowercase()) {
                    "true" -> true
                    "false" -> false
                    else -> error("wabbit.useMavenLocalArtifacts must be true or false, got '$value'")
                }
            }
            .orElse(false)
            .get()
    if (useLocalBuildOverridesInPluginManagement) {
    }
    repositories {
        if (useMavenLocalArtifactsInPluginManagement) {
            mavenLocal {
                content {
                    includeGroup("one.wabbit")
                    includeGroupByRegex("one\\.wabbit\\..+")
                }
            }
        }
        google()
        mavenCentral()
        gradlePluginPortal()

    }
    plugins {
        id("org.jetbrains.kotlin.jvm") version "2.3.10"
        id("org.jetbrains.kotlin.js") version "2.3.10"
        id("org.jetbrains.kotlin.multiplatform") version "2.3.10"
        id("org.jetbrains.kotlin.plugin.serialization") version "2.3.10"
        id("org.jetbrains.kotlin.plugin.compose") version "2.3.10"
        id("com.android.application") version "8.12.0"
        id("com.android.library") version "8.12.0"
        id("com.android.kotlin.multiplatform.library") version "8.12.0"
        id("org.jetbrains.compose") version "1.9.1"
        id("com.gradleup.shadow") version "8.3.0"
        id("org.jetbrains.dokka") version "2.0.0"
        id("org.jetbrains.kotlinx.kover") version "0.9.3"
        id("com.vanniktech.maven.publish") version "0.36.0"
        id("org.jetbrains.intellij") version "1.17.2"
        id("org.jetbrains.intellij.platform") version "2.10.4"
        id("io.papermc.paperweight.userdev") version "2.0.0-beta.17"
        id("net.minecrell.plugin-yml.bukkit") version "0.6.0"

    }
}

val localSettingsFile = file("settings.local.gradle.kts")
if (useLocalBuildOverrides && localSettingsFile.isFile) {
    apply(from = localSettingsFile)
}
