name: Docs Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: "21"
          cache: gradle


      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build Dokka docs
        run: ./gradlew --no-daemon build dokkaGeneratePublicationHtml

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/dokka/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
